
{{ config(
    materialized='table'
) }}

with events as (
    select * from {{ ref('int_events') }}
),

metrics as (
    select
        country,
        device_type,
        -- Null Handling: If no campaign, it's Organic
        coalesce(campaign_id, 'organic') as campaign_id,
        
        -- Campaign Hierarchy (Global -> Category -> Regional)
        -- Extract 'blackfriday' from 'cmp_US_blackfriday' or default to 'Organic'
        coalesce(split(campaign_id, '_')[safe_offset(2)], 'organic') as campaign_category,

        -- Pretty Name: "Blackfriday US"
        concat(initcap(coalesce(split(campaign_id, '_')[safe_offset(2)], 'organic')), ' ', country) as campaign_name,
        
        -- Metrics
        count(distinct session_id) as total_sessions,
        count(distinct user_id) as total_users,
        count(*) as total_events,
        
        -- Revenue Breakdown (Revenue generated by each action type)
        sum(case when action = 'purchase' then adjusted_value else 0 end) as revenue_from_sales,
        sum(case when action = 'click' then adjusted_value else 0 end) as revenue_from_clicks,
        sum(case when action = 'view' then adjusted_value else 0 end) as revenue_from_views,
        sum(adjusted_value) as total_revenue,
        
        sum(case when is_sale then 1 else 0 end) as total_purchases,
        sum(case when action = 'click' then 1 else 0 end) as total_clicks,
        sum(case when action = 'view' then 1 else 0 end) as total_views
        
    from events
    group by 1, 2, 3, 4, 5
)

select * from metrics
order by total_revenue desc
