version: 2

sources:
  - name: operational
    description: Operational/transactional data from PostgreSQL
    database: ecommerce
    schema: public
    tables:
      - name: orders
        description: E-commerce orders table
        columns:
          - name: order_id
            description: Unique order identifier
          - name: user_id
            description: User who placed the order
          - name: product_id
            description: Product in the order
          - name: timestamp
            description: Order timestamp
          - name: amount
            description: Order amount
          - name: status
            description: Order status
          - name: quantity
            description: Quantity ordered
      
      - name: page_views
        description: Page view events table
        columns:
          - name: view_id
            description: Unique page view identifier
          - name: user_id
            description: User who viewed the page
          - name: product_id
            description: Product viewed (if applicable)
          - name: timestamp
            description: View timestamp
          - name: session_id
            description: Session identifier
          - name: page_url
            description: URL of the page viewed
          - name: duration_seconds
            description: Time spent on page in seconds
      
      - name: inventory_changes
        description: Inventory change events table
        columns:
          - name: id
            description: Unique inventory change identifier
          - name: product_id
            description: Product identifier
          - name: timestamp
            description: Change timestamp
          - name: stock_change
            description: Change in stock quantity
          - name: current_stock
            description: Current stock level
          - name: warehouse_id
            description: Warehouse identifier
      
      - name: users
        description: User dimension table
        columns:
          - name: user_id
            description: Unique user identifier
          - name: signup_date
            description: User signup date
          - name: country
            description: User country
          - name: tier
            description: User tier/segment
      
      - name: products
        description: Product dimension table
        columns:
          - name: product_id
            description: Unique product identifier
          - name: category
            description: Product category
          - name: price
            description: Product price
          - name: supplier
            description: Product supplier


