ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5433
      dbname: ecommerce
      schema: analytics
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10


